import React, { useState } from 'react';
import {Text, Image, View, StyleSheet} from 'react-native';
import {______Main} from '../../components/______Main';
import { TextInput } from 'react-native-gesture-handler';
const rightArrow9 = '../../assets/images/rightArrow9.png';
const schedule1 = '../../assets/images/schedule1.png';

export interface CityToCityLoadingProps {
  testID?: string;
}

export function Intercity(props: CityToCityLoadingProps) {
  const [data,setData] = useState({
    from:'',
    to: '',
    
  })
  return (
    <View style={styles.root} 
    >
      <TextInput value=/>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    width: 393,
    height: 852,
    backgroundColor: 'rgba(30, 30, 30, 1)',
  },
  ________________: {
    width: 437,
    height: 36,
    flexShrink: 0,
    color: 'rgba(200, 188, 206, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 19,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  _______________: {
    width: 437,
    height: 36,
    flexShrink: 0,
    color: 'rgba(118, 118, 118, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 19,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  ______Main: {
    width: 94,
    height: 36,
    flexShrink: 0,
    color: 'rgba(200, 188, 206, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  ______Main2: {
    width: 268,
    height: 36,
    flexShrink: 0,
    color: 'rgba(200, 188, 206, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 19,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  ______Main3: {
    width: 94,
    height: 36,
    flexShrink: 0,
    color: 'rgba(118, 118, 118, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  a: {
    width: 47,
    height: 36,
    flexShrink: 0,
    color: 'rgba(0, 0, 0, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  b: {
    width: 47,
    height: 36,
    flexShrink: 0,
    color: 'rgba(0, 0, 0, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  _____________189: {
    width: 293,
    height: 32,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  _______________167: {
    width: 293,
    height: 32,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  ____________145: {
    width: 293,
    height: 32,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  ______________100: {
    width: 293,
    height: 32,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  ________________2: {
    width: 437,
    height: 36,
    flexShrink: 0,
    color: 'rgba(200, 188, 206, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 19,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  _______________2: {
    width: 437,
    height: 36,
    flexShrink: 0,
    color: 'rgba(118, 118, 118, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 19,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  ______Main5: {
    width: 268,
    height: 36,
    flexShrink: 0,
    color: 'rgba(200, 188, 206, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 19,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  ______Main6: {
    width: 94,
    height: 36,
    flexShrink: 0,
    color: 'rgba(118, 118, 118, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  a2: {
    width: 47,
    height: 36,
    flexShrink: 0,
    color: 'rgba(0, 0, 0, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  b2: {
    width: 47,
    height: 36,
    flexShrink: 0,
    color: 'rgba(0, 0, 0, 1)',
    textAlign: 'center',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 20,
  },
  _____________1892: {
    width: 293,
    height: 32,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  _______________1672: {
    width: 293,
    height: 32,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  ____________1452: {
    width: 293,
    height: 32,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  ______________1002: {
    width: 293,
    height: 32,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Noto Rashi Hebrew',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  _______: {
    width: 54,
    height: 20,
    flexShrink: 0,
    color: 'rgba(46, 97, 229, 1)',
    fontFamily: 'Inter',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  _________: {
    width: 73,
    height: 20,
    flexShrink: 0,
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Inter',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
});
